[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.pdo_sqlite",
  "php82Extensions.mbstring",
  "php82Extensions.bcmath",
  "php82Extensions.tokenizer",
  "php82Extensions.fileinfo",
  "php82Extensions.openssl",
  "nginx",
  "nodejs",
  "python311Packages.supervisor"
]

[phases.build]
cmds = [
  "php82Packages.composer install --no-dev --optimize-autoloader || true",
  "chmod +x assets/start.sh"
]

[start]
cmd = "bash assets/start.sh"
